name: Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        python-version: [3.7]
        example:
          - "examples/gecko-sdk-ble-thunderboard"
          - "examples/gecko-sdk-blink-baremetal"
          - "examples/gecko-sdk-cpp"
          - "examples/gecko-sdk-iostream-usart-baremetal"
        exclude:
          - {os: windows-latest, example: "examples/zephyr-custom-module"}
          - {python-version: 2.7, example: "examples/zephyr-blink"}
          - {python-version: 2.7, example: "examples/zephyr-custom-module"}
          - {python-version: 2.7, example: "examples/zephyr-subsys-console-getline"}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          platformio platform install file://.
      - name: Build examples
        run: |
          platformio run -d ${{ matrix.example }}
